ML_AUTO_ACCEPT_CONFIDENCE = 0.85
ML_AUTO_ACCEPT_MARGIN = 0.15
ML_SAFETY_THRESHOLD = 0.35

STRONG_EXISTING_CONTENT_THRESHOLD = 0.88
SIMILAR_CONTENT_THRESHOLD = 0.75
METADATA_EXISTING_CONTENT_THRESHOLD = 0.70
EMBEDDING_EXISTING_CONTENT_THRESHOLD = 0.58
EMBEDDING_SIMILAR_CONTENT_THRESHOLD = 0.55
EMBEDDING_POSSIBLE_DUPLICATE_METADATA_SUPPORT_THRESHOLD = 0.65
LOW_CONFIDENCE_REVIEW_THRESHOLD = 0.75
POSSIBLE_DUPLICATE_REVIEW_MIN_SCORE = 0.70
POSSIBLE_DUPLICATE_REVIEW_MAX_SCORE = 0.82

CONTENT_GAP_MIN_REQUESTS = 5
CONTENT_GAP_SIMILARITY_THRESHOLD = 0.25
CONTENT_GAP_STRONG_TEXT_SIMILARITY_THRESHOLD = 0.45
CONTENT_GAP_SEMANTIC_SIMILARITY_THRESHOLD = 0.64
CONTENT_GAP_SEMANTIC_SEED_SIMILARITY_THRESHOLD = 0.56
CONTENT_GAP_SEMANTIC_NEIGHBORHOOD_COHESION_THRESHOLD = 0.50
CONTENT_GAP_REFINE_SEMANTIC_SIMILARITY_THRESHOLD = 0.72
